/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 */

package com.ai.plug.core.spec.utils.elicitation;

import io.modelcontextprotocol.spec.McpSchema;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests for {@link McpElicitation#buildElicitationUrlRequest(String, String)} and
 * {@link McpElicitation#buildElicitationUrlRequest(String, String, String)} —
 * the URL-mode elicitation support introduced for MCP protocol 2025-11-25.
 */
class ElicitUrlRequestTest {

    private final McpElicitation elicit = new McpElicitation() {
        @Override
        public McpSchema.ElicitResult elicit(String message, Class<?> schema) {
            return null;
        }

        @Override
        public reactor.core.publisher.Mono<McpSchema.ElicitResult> elicitAsync(String message, Class<?> schema) {
            return reactor.core.publisher.Mono.empty();
        }
    };

    @Test
    void buildElicitationUrlRequest_autoGeneratedIdIsNonBlankUuid() {
        McpSchema.ElicitUrlRequest req = elicit.buildElicitationUrlRequest(
            "Please confirm your account", "https://example.com/oauth/authorize");
        assertThat(req.message()).isEqualTo("Please confirm your account");
        assertThat(req.url()).isEqualTo("https://example.com/oauth/authorize");
        assertThat(req.mode()).isEqualTo("url");
        // ElicitUrlRequest carries its server-side correlation id; the field name is
        // inherited from the Record — confirm it is present and non-blank.
        // We assert via the string-encoded form rather than reaching into private fields.
        assertThat(req.toString()).contains("https://example.com/oauth/authorize");
    }

    @Test
    void buildElicitationUrlRequest_explicitIdRespected() {
        McpSchema.ElicitUrlRequest req = elicit.buildElicitationUrlRequest(
            "msg", "https://example.com/cb", "order-42");
        assertThat(req.toString()).contains("order-42");
        assertThat(req.message()).isEqualTo("msg");
        assertThat(req.url()).isEqualTo("https://example.com/cb");
    }

    @Test
    void buildElicitationFormRequest_schemaWrappedWhenNotObject() {
        // The form-mode path still wraps non-object types. Probe with String.class
        // (which victools generates as {"type":"string"}) and ensure the call path
        // returns a valid ElicitFormRequest without throwing.
        McpSchema.ElicitFormRequest req = elicit.buildElicitationRequest("greet", String.class);
        assertThat(req.message()).isEqualTo("greet");
        assertThat(req.mode()).isEqualTo("form");
        // requestedSchema for String.class is wrapped as {"type":"object","properties":{"value":{...}}}
        assertThat(req.requestedSchema()).containsKey("type").containsKey("properties");
        assertThat(req.requestedSchema().get("type")).isEqualTo("object");
    }
}