spring:
  application:
    name: plug
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  ai:
    mcp:
      server:
        name: test-mcp
        version: 1.0.0
        type: SYNC

management:
  endpoints:
    web:
      exposure:
        include: beans


plugin:
  mcp:
    enabled: true
server:
  tomcat:
    connection-timeout: 60s