spring:
  application:
    name: plug
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: test-mcp
        version: 1.0.0
        type: SYNC
        tool-response-mime-type:
          readJPEGImage: image/jpg


plugin:
  mcp:
    enabled: true
    parser:
      param: MCPTOOL, JAVADOC, TOOL,
      des: MCPTOOL, JAVADOC, TOOL, JACKSON, SWAGGER3, SWAGGER2
    scope: interface
    resource:
      enabled: true
    tool:
      enabled: true
    complete:
      enabled: true
    prompt:
      enabled: true

logging:
  level:
    org.springframework.ai: DEBUG
    io.modelcontextprotocol: DEBUG
    com.ai.plug: DEBUG




